### ISSUE TITLE
[BUG] Crypto assets wrong color/arrow

### ISSUE THREAD

**Issue by Lerwox** [matextrem/streamdeck-tickertap#13]
**Describe the bug**
I've added a crypto asset to the app, on coin market I can see that the price is falling, but the app shows it as rising (arrow up and green colour).

**To Reproduce**
1. Add item
2. Set tiker with `TA-DA` (https://coinmarketcap.com/currencies/ta-da/)
3. Set type `Crytpo`

**Expected behavior**
I'd really like the right colour and the right arrow to be displayed.

**Screenshots**
![image](https://github.com/user-attachments/assets/c78958ce-01be-4b78-9cd7-23d2b6fc7be3)
![image](https://github.com/user-attachments/assets/1d12b9c0-0e44-40eb-a1c7-69ac81344e26)
![image](https://github.com/user-attachments/assets/797974cb-1170-492d-bb07-b82e757ea4ad)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.2.0

**Additional context**
It's the only crypto I have a problem with. The others work perfectly, whether you're in a rising or a falling market.

**Comment by matextrem** [comment]
Hey @Lerwox ! It seems `CoinMarketCap` is caching the response for the percentage value (You can check it when you reload the page, you'll see first a number is loaded and then the new one is updated). As JS cannot be loaded to get this data, we need to wait for it to be refreshed and according to my testing, it happens every 5 minutes or so.

**Comment by Lerwox** [comment]
Hey @matextrem, 
the fact is that your app currently has a bug. Because the color and direction of the arrow don't correlate with the percentage displayed.

A super simple fix is in the `drawQuoteImage` method to base it on the `percentage` variable (which from what I understand corresponds to the percentage change), rather than the `change` variable.
In fact, you can see in the method that it's only the `percentage` variable that's displayed (I do not see any display of the real price change), so it would make sense to correlate the direction of the arrow and the color with the `percentage` variable.

But I didn't analyze all the code, just the method for drawing the whole thing and the CoinMarketCap provider. So if I've missed anything, don't hesitate to let me know 😉

**Comment by matextrem** [comment]
Hey @Lerwox! I could do that but I don't think it's gonna fix the issue cause the change variable has the price change difference rather than the percentage but in terms of change it is the same (it is negative when the active is decreasing and positive when it's increasing). 

The actual issue is what I mentioned above. CoinMarketCap is caching the percentage change when JS is not enabled so if it's not updated if you have it disabled. You can easily check this going to the CoinMarketCap asset page, disable JS and reload the page, and then in another window with JS enable, go to the same asset page and compare the values. You'll see that in the page with JS disabled, the value will not reflect the updated one (but a previous one) 

After some minutes (it seems it's about 5/6 minutes), it is updated.

**Comment by Lerwox** [comment]
Thanks for the quick reply @matextrem.

I understand what you mean, the token price (and its price evolution) are updated correctly. Where as the percentage change is cached. Is this correct?

So if I understand correctly, it's either we have the most up-to-date values, but the percentage change is likely to be decorrelated. Or we use the cached value, no decorrelation but arrow direction and color not up to date.
Am I mistaken?

In terms of pure UX/UI, I'd find it logical to have a correlation of the data, too bad for the actuality of the data.
Or maybe you need to find another site that doesn't use this caching method.

**Comment by matextrem** [comment]
@Lerwox Yeah, you got it right. 

We can either use another site for fetching crypto data without values being cached or use the cached value in order for the data to be correlated even though they are not the up to date values. In that case, I could do what you suggest about using the percentage instead of the change variable. 

WDYT?

**Comment by Lerwox** [comment]
Okay cool, I'm happy to help.

Above all, having correlated data is the most important thing in my opinion.
After that, to solve the problem of the most up-to-date data, maybe using coingecko.com (which doesn't seem to have a cache) could be a solution.

**Comment by matextrem** [comment]
@Lerwox I've created a new version with the Fix we discussed https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.2.1

I'll be analysing the option of using CoinGecko instead for future releases.

**Comment by Lerwox** [comment]
@matextrem Nice !

It works like a charm, thank you !
