### ISSUE TITLE
Can't retrieve crypto prices

### ISSUE THREAD

**Issue by BlastFutures** [matextrem/streamdeck-tickertap#3]
**Describe the bug**

**To Reproduce**
1. Go to 'Crypto`
2. Enter "BITCOIN"
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matextrem** [comment]
Hey @BlastFutures ! This was already reported and fixed in here https://github.com/matextrem/streamdeck-tickertap/issues/2

You can download the latest version from [here](https://github.com/matextrem/streamdeck-tickertap/raw/main/release/com.matextrem.tickertap.streamDeckPlugin). I'll be sending an email to elgato in order to upload the new version in the store.

**Comment by polaroi8d** [comment]
Thanks the new version solved the issue. Greate works guys!
